-- ═══════════════════════════════════════════════════════════════════════════
-- TradeMirror OS — Phase 1 one-shot setup (run ONCE on a fresh project)
--
-- Paste this whole file into the Supabase dashboard → SQL Editor and Run.
-- It is generated by concatenating, in order:
--   migrations/20260626120000_init_schema.sql
--   migrations/20260626120050_auth_helpers.sql
--   migrations/20260626120100_storage.sql
--   migrations/20260626120200_rls.sql
--   seed.sql
-- then a Phase-1 auth fix (confirm the seeded auth users + create profiles).
--
-- Prereq for the auth fix: create the auth user superadmin@chipafarm.com first
-- (Auth → Users → Add user), or run `npm run seed:users` with a service role
-- key. This script confirms it and wires the matching public.users profile so
-- the app's hardcoded admin session (dev auto-login) and RLS work.
-- ═══════════════════════════════════════════════════════════════════════════
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
-- TradeMirror OS â€” schema foundation (PRD Â§14)
-- Enums, the seven tables, relationships, indexes, and the updated_at trigger.
-- No business logic: the only computed values are the two columns the PRD
-- marks "-- computed" (total_costs, net_profit), implemented as generated
-- columns so the database enforces the invariant.
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

-- â”€â”€ Enums (PRD Â§3, Â§9.2, Â§10.1, Â§10.3) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create type public.user_role as enum ('super_admin', 'internal', 'partner');
create type public.milestone_status as enum ('pending', 'received', 'overdue');
create type public.document_type as enum (
  'frigo_contract', 'sales_contract', 'signed_contract', 'bol', 'other'
);
create type public.trade_status as enum (
  'draft', 'active', 'advance_received', 'shipped', 'balance_received', 'overdue'
);

-- â”€â”€ users (id matches Supabase Auth user id) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.users (
  id            uuid primary key references auth.users (id) on delete cascade,
  email         text not null unique,
  full_name     text not null,
  role          public.user_role not null,
  is_active     boolean not null default true,
  invited_at    timestamptz,
  last_login_at timestamptz,
  created_at    timestamptz not null default now()
);

-- â”€â”€ entities (the EAS / LLC operational toggle) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.entities (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  country    text not null,
  ruc_ein    text not null,
  address    text not null,
  city       text not null,
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

-- â”€â”€ bank_profiles (one or more per entity) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.bank_profiles (
  id                      uuid primary key default gen_random_uuid(),
  entity_id               uuid not null references public.entities (id) on delete cascade,
  profile_name            text not null,
  beneficiary_name        text not null,
  beneficiary_address     text not null,
  intermediary_bank_name  text not null,
  intermediary_bank_swift text not null,
  bank_name               text not null,
  bank_swift              text not null,
  account_number          text not null,
  ara_number              text,
  field_71a               text not null default 'OUR',
  is_default              boolean not null default false,
  created_at              timestamptz not null default now()
);

-- â”€â”€ clients (buyers) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.clients (
  id            uuid primary key default gen_random_uuid(),
  company_name  text not null,
  address       text not null,
  city          text not null,
  country       text not null,
  tax_id        text not null,
  contact_name  text not null,
  contact_email text not null,
  contact_phone text not null,
  notes         text,
  created_at    timestamptz not null default now()
);

-- â”€â”€ contacts (internal address book) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.contacts (
  id         uuid primary key default gen_random_uuid(),
  full_name  text not null,
  phone      text not null,
  email      text not null,
  role       text,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

-- â”€â”€ trades â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.trades (
  id                  uuid primary key default gen_random_uuid(),
  trade_reference     text not null unique,
  entity_id           uuid not null references public.entities (id),
  bank_profile_id     uuid not null references public.bank_profiles (id),
  client_id           uuid not null references public.clients (id),
  contact_id          uuid not null references public.contacts (id),
  contract_date       date not null,
  signing_date        date,
  bol_date            date,
  frigo_contract_ref  text not null,
  quantity_tons       numeric(14, 3) not null,
  product_description text not null,
  frigo_unit_price    numeric(14, 4) not null,
  frigo_total         numeric(14, 2) not null,
  sale_unit_price     numeric(14, 4) not null,
  sale_total          numeric(14, 2) not null,
  shipping_cost       numeric(14, 2) not null default 0,
  insurance_cost      numeric(14, 2) not null default 0,
  bank_fees           numeric(14, 2) not null default 0,
  -- PRD Â§9.1 "-- computed": enforced by the database, not the app.
  total_costs numeric(14, 2)
    generated always as (frigo_total + shipping_cost + insurance_cost + bank_fees) stored,
  net_profit numeric(14, 2)
    generated always as (sale_total - (frigo_total + shipping_cost + insurance_cost + bank_fees)) stored,
  advance_status      public.milestone_status not null default 'pending',
  advance_received_at timestamptz,
  balance_status      public.milestone_status not null default 'pending',
  balance_received_at timestamptz,
  trade_status        public.trade_status not null default 'draft',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- â”€â”€ documents (Trade Folder metadata; files live in Storage) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.documents (
  id            uuid primary key default gen_random_uuid(),
  trade_id      uuid not null references public.trades (id) on delete cascade,
  document_type public.document_type not null,
  file_name     text not null,
  storage_path  text not null,
  uploaded_by   uuid not null references public.users (id),
  uploaded_at   timestamptz not null default now()
);

-- â”€â”€ Indexes on foreign keys and common lookups â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create index idx_bank_profiles_entity_id on public.bank_profiles (entity_id);
create index idx_trades_entity_id        on public.trades (entity_id);
create index idx_trades_bank_profile_id  on public.trades (bank_profile_id);
create index idx_trades_client_id        on public.trades (client_id);
create index idx_trades_contact_id       on public.trades (contact_id);
create index idx_trades_trade_status     on public.trades (trade_status);
create index idx_documents_trade_id      on public.documents (trade_id);
create index idx_documents_uploaded_by   on public.documents (uploaded_by);

-- At most one default contact, and one default bank profile per entity
-- (PRD Â§4.2 / Â§6.1). Pure schema integrity, no application logic.
create unique index uq_contacts_single_default
  on public.contacts (is_default) where is_default;
create unique index uq_bank_profiles_default_per_entity
  on public.bank_profiles (entity_id) where is_default;

-- â”€â”€ updated_at maintenance for trades â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_trades_set_updated_at
  before update on public.trades
  for each row execute function public.set_updated_at();


-- ───────────────────────────────────────────────────────────────────────────
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
-- RLS helper functions.
--
-- SECURITY DEFINER so they read public.users without triggering that table's
-- own RLS (which would otherwise recurse). They resolve the current request's
-- app role and active flag from the users profile, keyed by auth.uid().
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

create or replace function public.current_app_role()
returns public.user_role
language sql stable security definer set search_path = public as $$
  select role from public.users where id = auth.uid();
$$;

create or replace function public.is_active_user()
returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce((select is_active from public.users where id = auth.uid()), false);
$$;

create or replace function public.is_super_admin()
returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select role = 'super_admin' from public.users where id = auth.uid()),
    false
  );
$$;

revoke all on function public.current_app_role() from public;
revoke all on function public.is_active_user() from public;
revoke all on function public.is_super_admin() from public;

grant execute on function public.current_app_role() to authenticated;
grant execute on function public.is_active_user() to authenticated;
grant execute on function public.is_super_admin() to authenticated;


-- ───────────────────────────────────────────────────────────────────────────
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
-- Storage: the single private bucket that backs every Trade Folder.
-- Object access mirrors the documents table policies (PRD Â§3.4):
--   read   â†’ any active user (download)
--   upload â†’ super_admin or internal
--   modify â†’ super_admin only
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

insert into storage.buckets (id, name, public)
values ('trade-documents', 'trade-documents', false)
on conflict (id) do nothing;

create policy "trade docs: read for active users"
  on storage.objects for select to authenticated
  using (bucket_id = 'trade-documents' and public.is_active_user());

create policy "trade docs: upload for staff"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'trade-documents'
    and public.is_active_user()
    and public.current_app_role() in ('super_admin', 'internal')
  );

create policy "trade docs: update for admin"
  on storage.objects for update to authenticated
  using (bucket_id = 'trade-documents' and public.is_super_admin())
  with check (bucket_id = 'trade-documents' and public.is_super_admin());

create policy "trade docs: delete for admin"
  on storage.objects for delete to authenticated
  using (bucket_id = 'trade-documents' and public.is_super_admin());


-- ───────────────────────────────────────────────────────────────────────────
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
-- Row Level Security â€” enforces the PRD Â§3.4 permission matrix at the database.
--
-- Table grants give the `authenticated` Postgres role the privilege; the
-- policies below decide which rows each app role may touch. Column-level
-- financial visibility (hiding Frigo price / financials from Internal) is a
-- column concern handled by the trades feature's queries, not row policies.
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

grant usage on schema public to authenticated;
grant select, insert, update, delete on
  public.users, public.entities, public.bank_profiles, public.clients,
  public.contacts, public.trades, public.documents
to authenticated;

alter table public.users         enable row level security;
alter table public.entities      enable row level security;
alter table public.bank_profiles enable row level security;
alter table public.clients       enable row level security;
alter table public.contacts      enable row level security;
alter table public.trades        enable row level security;
alter table public.documents     enable row level security;

-- â”€â”€ users: read own profile; only SuperAdmin manages users (PRD Â§2.4) â”€â”€â”€â”€
create policy "users: read self or admin" on public.users
  for select to authenticated
  using (id = auth.uid() or public.is_super_admin());
create policy "users: admin insert" on public.users
  for insert to authenticated with check (public.is_super_admin());
create policy "users: admin update" on public.users
  for update to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());
create policy "users: admin delete" on public.users
  for delete to authenticated using (public.is_super_admin());

-- â”€â”€ entities: readable by any active user (for trade display); admin writes â”€
create policy "entities: read active" on public.entities
  for select to authenticated using (public.is_active_user());
create policy "entities: admin write" on public.entities
  for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());

-- â”€â”€ bank_profiles: SuperAdmin only â€” they hold beneficiary account data â”€â”€
create policy "bank_profiles: admin only" on public.bank_profiles
  for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());

-- â”€â”€ clients: SuperAdmin full, Internal view-only, Partner none (PRD Â§3.4) â”€
create policy "clients: read staff" on public.clients
  for select to authenticated
  using (public.current_app_role() in ('super_admin', 'internal'));
create policy "clients: admin write" on public.clients
  for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());

-- â”€â”€ contacts: SuperAdmin only (PRD Â§3.4) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create policy "contacts: admin only" on public.contacts
  for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());

-- â”€â”€ trades: all active users read; only SuperAdmin writes (PRD Â§3.4) â”€â”€â”€â”€â”€
create policy "trades: read active" on public.trades
  for select to authenticated using (public.is_active_user());
create policy "trades: admin write" on public.trades
  for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());

-- â”€â”€ documents: all read; staff upload; admin modify (PRD Â§3.4) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create policy "documents: read active" on public.documents
  for select to authenticated using (public.is_active_user());
create policy "documents: staff insert" on public.documents
  for insert to authenticated
  with check (
    public.is_active_user()
    and public.current_app_role() in ('super_admin', 'internal')
  );
create policy "documents: admin update" on public.documents
  for update to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());
create policy "documents: admin delete" on public.documents
  for delete to authenticated using (public.is_super_admin());


-- ───────────────────────────────────────────────────────────────────────────
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
-- Seed data (idempotent). Covers entities, a sample banking profile, a sample
-- client, and a sample contact. The three platform users (SuperAdmin /
-- Internal / Partner) are created by scripts/seed-auth-users.mjs, because auth
-- users must be provisioned through Supabase Auth, not raw SQL.
--
-- Values marked PENDING are admin-input fields in the PRD (Â§4.1) with no value
-- in the source documents; they are placeholders to keep NOT NULL satisfied.
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

-- â”€â”€ Entities: the EAS â†’ LLC operational toggle (PRD Â§4.1) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
insert into public.entities (id, name, country, ruc_ein, address, city, is_active)
values
  (
    '11111111-1111-1111-1111-111111111111',
    'Chipa Tech E.A.S.', 'Paraguay', 'PENDING',
    'Calle Dr. Eusebio Lilio y Bernardino Caballero #2880', 'Asuncion', true
  ),
  (
    '22222222-2222-2222-2222-222222222222',
    'Chipa Farm LLC', 'USA (Wyoming)', 'PENDING',
    'PENDING', 'PENDING', true
  )
on conflict (id) do nothing;

-- â”€â”€ Sample banking profile for the EAS entity (mirrors 701-2026 routing) â”€
insert into public.bank_profiles (
  id, entity_id, profile_name, beneficiary_name, beneficiary_address,
  intermediary_bank_name, intermediary_bank_swift, bank_name, bank_swift,
  account_number, ara_number, field_71a, is_default
)
values (
  '33333333-3333-3333-3333-333333333333',
  '11111111-1111-1111-1111-111111111111',
  'EAS â€” Banco Nacional de Fomento',
  'Chipa Tech E.A.S.', 'Asuncion, Paraguay',
  'CITIBANK NA', 'CITIUS33',
  'BANCO NACIONAL DE FOMENTO', 'BNFAPYPAXXX',
  '000000000000', null, 'OUR', true
)
on conflict (id) do nothing;

-- â”€â”€ Sample client / buyer (701-2026 destination: Alexandria, Egypt) â”€â”€â”€â”€â”€
insert into public.clients (
  id, company_name, address, city, country, tax_id,
  contact_name, contact_email, contact_phone, notes
)
values (
  '44444444-4444-4444-4444-444444444444',
  'Al Manara Trading LLC', '14 Corniche Road', 'Alexandria', 'Egypt', 'EG-000000000',
  'Mohamed Said', 'buyer@almanara.example', '+20 100 000 0000',
  'Sample buyer record for development.'
)
on conflict (id) do nothing;

-- â”€â”€ Sample contact (the trade-desk contact from the source contract) â”€â”€â”€â”€
insert into public.contacts (id, full_name, phone, email, role, is_default)
values (
  '55555555-5555-5555-5555-555555555555',
  'Ali Kanso', '+20 1017299515', 'ali@chipafarm.com', 'Trade Desk', true
)
on conflict (id) do nothing;


-- ═══════════════════════════════════════════════════════════════════════════
-- Phase-1 auth fix — confirm seeded auth users and ensure their profiles exist.
-- ═══════════════════════════════════════════════════════════════════════════
update auth.users
   set email_confirmed_at = coalesce(email_confirmed_at, now())
 where email in ('superadmin@chipafarm.com','internal@chipafarm.com','partner@chipafarm.com');

insert into public.users (id, email, full_name, role, is_active)
select u.id,
       u.email,
       case u.email
         when 'superadmin@chipafarm.com' then 'Chipa Owner'
         when 'internal@chipafarm.com'   then 'Internal Staff'
         else 'Finance Partner'
       end,
       (case u.email
         when 'superadmin@chipafarm.com' then 'super_admin'
         when 'internal@chipafarm.com'   then 'internal'
         else 'partner'
       end)::public.user_role,
       true
  from auth.users u
 where u.email in ('superadmin@chipafarm.com','internal@chipafarm.com','partner@chipafarm.com')
on conflict (id) do update set role = excluded.role, is_active = true;
